version: "3.8"

services:
  eureka-server:
    build: eureka-server/
    ports:
      - "8761:8761"
    expose:
      - 8761
    container_name: eureka-server
    networks:
      - kata

  config:
    build: config/
    expose:
      - 8886
    container_name: config
    depends_on:
      - eureka-server
    networks:
      - kata

#  bill-service:
#    build: bill-service/
#    expose:
#      - 0
#    container_name: bill-service
#    depends_on:
#      - eureka-server
#
#  person-service:
#    build: person-service/
#    expose:
#      - 0
#    container_name: person-service
#    depends_on:
#      - eureka-server

  materials-service:
    build: materials-service/
    expose:
      - 0
    container_name: materials-service
    depends_on:
      - config
    networks:
      - kata

  gateway:
    build: gateway/
    expose:
      - 4444
    ports:
      - "4444:4444"
    container_name: gateway
    depends_on:
      - materials-service
    networks:
      - kata

networks:
  kata:
    driver: "bridge"